### ISSUE TITLE
Missing Tags / Releases

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/content_type_clone#3]
Opening this issue to provide some documentation of a little mess that happened this evening. 

While working on a PR for this module, I made a error with my fork of the repo and decided to delete it and start over. While not a maintainer of this module, it turns out that I have access to delete repos and accidentally deleted the main repo instead of my fork. 

Since I had a copy of the repo, I was able to restore the module and commit history of 1.x-1.x branch, but in the process we lost previous releases/tags and any release notes. I don't think these are necessary and I don't know how to restore them. 

Opening this issue to provide information about what happened, in case someone is trying to figure this out in the future. 

NOTE: There was one open issue in the queue, which I also lost. But, I had that issue open in my browser and just went ahead and fixed the small css issue. 

I Created a new release (1.x-1.0.4) with the fix to the bug I found and the css bug. I created a fresh demo site and testing the new release on that site to confirm tha both bugs are fixed. 

Atten: @laryn

**Comment by laryn** [comment]
Thanks for the transparency, Tim. I think your administrative role gives you a lot of power that most people don't have over contrib.

I've checked things over and it looks like you've merged a PR and made a bug fix to it, and also added a fix for removal of the `!important` flag in the CSS.

It's a small enough history that I'll go through the commits that have issue numbers on them and "recreate" shells of those issues with links to the commits, and at this point I think we just move forward and open any new tickets as needed. Thanks for your work and no worries about the mixup: no harm no foul!

**Comment by laryn** [comment]
Original Issue #3: Exclude non-entity fields like Rabbit Hole:
https://github.com/backdrop-contrib/content_type_clone/commit/5561541a2ec95201043c840f9b0492e892ad029c
